import axios from "axios";

export const api = axios.create({
  baseURL: "http://localhost:3001/",
  timeout: 3000,
});

export const token =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhcmFhaDhAZW1haWwuY29tIiwic3ViIjozMSwibmFtZSI6IlNhcmFoIFNpbHZhMiIsInVzZXJSb2xlcyI6W3siaWQiOjIsInVzZXJJZCI6MzEsInBlcm1pc3Npb25JZCI6NTYsInBoYXNlSWQiOjEsInBlcm1pc3Npb24iOnsiaWQiOjU2LCJuYW1lIjoiQ3JpYWRvckFDVCIsImNhbl9jcmVhdGUiOnRydWUsImNhbl9yZWFkIjp0cnVlLCJjYW5fdXBkYXRlIjp0cnVlLCJjYW5fZGVsZXRlIjp0cnVlLCJjYW5fYXBwcm92ZSI6ZmFsc2V9fSx7ImlkIjozLCJ1c2VySWQiOjMxLCJwZXJtaXNzaW9uSWQiOjU3LCJwaGFzZUlkIjoyLCJwZXJtaXNzaW9uIjp7ImlkIjo1NywibmFtZSI6IkFkbWluQUNUIiwiY2FuX2NyZWF0ZSI6dHJ1ZSwiY2FuX3JlYWQiOnRydWUsImNhbl91cGRhdGUiOnRydWUsImNhbl9kZWxldGUiOnRydWUsImNhbl9hcHByb3ZlIjp0cnVlfX0seyJpZCI6NCwidXNlcklkIjozMSwicGVybWlzc2lvbklkIjo1OCwicGhhc2VJZCI6MywicGVybWlzc2lvbiI6eyJpZCI6NTgsIm5hbWUiOiJBcHJvdmFkb3JBQ1QiLCJjYW5fY3JlYXRlIjpmYWxzZSwiY2FuX3JlYWQiOnRydWUsImNhbl91cGRhdGUiOmZhbHNlLCJjYW5fZGVsZXRlIjpmYWxzZSwiY2FuX2FwcHJvdmUiOnRydWV9fV0sImRlcGFydG1lbnRJZCI6MywiaWF0IjoxNzM3NDA2MzE5LCJleHAiOjE3Mzk5OTgzMTl9.bUedUKrP1YzFRHU4Prjz5r-7mbWG6CWt__ppSBWW9X4";
